export default {
    icGreenMarker: require("../assets/images/greenMarker.png"),
    busIcon: require("../assets/images/bus-icon-1.png"),
    greenIndicator: require("../assets/images/greenIndicator.png"),
    icBike: require("../assets/images/bike.png"),
    bus: require('../assets/images/logo1.png'),
    boardBus: require('../assets/images/BoardBus.png'),
    busStop1: require('../assets/images/BusStop1.png'),
    busStop: require('../assets/images/bus-stop.jpeg'),
    travel: require('../assets/images/Travel.png'),
    facebook: require('../assets/images/facebook.png'),
    map: require('../assets/images/map.jpeg'),
    projectlogo: require ('../assets/images/projectLogo.png'),
    google: require('../assets/images/google.png'),
}
